import { useState } from "react"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import Header from "@components/Header"
import Container from "@components/Container"
import Button from "@components/Button"
import styles from "@styles/Home.module.scss"
import products from "@data/products.json"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main>
        <Container>
          <h1>Jim's Bookself. Covers </h1>
          <h2>Available Books</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    width='1322'
                    height='2000'
                    src={product.image}
                    alt={`Cover of ${product.title}`}
                  />
                  <h3 className={styles.productTitles}>{product.title}</h3>
                  <p className={styles.productPrice}>${product.price}</p>
                  <p>
                    <Button
                      className='snipcart-add-item'
                      data-item-id={product.id}
                      data-item-price={product.price}
                      data-item-url='/'
                      data-item-description=''
                      data-item-image={product.image}
                      data-item-name={product.title}
                    >
                      Add to Cart
                    </Button>
                  </p>
                </li>
              )
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Jim's Bookself, Covers. {new Date().getFullYear()}
      </footer>
    </div>
  )
}
